from_latest_tag = true
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[bump_profiles]

[changelog]

[commit_types]

[git_hooks.commit-msg]
script = """#!/usr/bin/env bash
set -e
cog verify --file $1
cog check || true
"""

[git_hooks.pre-push]
script = """#!/usr/bin/env bash
if command -v nix >/dev/null \
  && [ -f /etc/nix/nix.conf ] \
  && [[ "$(grep -E '^experimental-features =' /etc/nix/nix.conf | awk -F'=' '{print $2}' | xargs)" =~ (flakes|nix-commands) ]]
then
  system=$(nix eval --impure --expr "builtins.currentSystem")
  nix build ".#checks.$system.all"
else
  >&2 echo "WARNING: Nix Flakes and/or new commands are not enabled! Evaluation checks will not be performed."
fi
"""
