[book]
title = "NixKraken docs"
authors = ["Nicolas Goudry"]
description = "Documentation for NixKraken Home Manager module"
language = "en"
# multilingual = false
# src = "src"

[preprocessor.alerts]
renderers = ["html", "linkcheck"]

[preprocessor.mermaid]

[output.html]
additional-css = [
  "theme/css/main.css",
  "theme/css/toc.css"
]
additional-js = [
  "theme/js/vendor/mermaid.tiny.js",
  "theme/js/main.js",
  "theme/js/mermaid.js",
  "theme/js/toc.js"
]
git-repository-url = "https://github.com/nicolas-goudry/nixkraken"
edit-url-template = "https://github.com/nicolas-goudry/nixkraken/edit/main/docs/{path}"
hash-files = true

[output.html.fold]
enable = true
level = 0

[output.linkcheck]
follow-web-links = true
warning-policy = "error"
# Exclude generated content link checks
exclude = [
  "cataas.com",
  "profiles.md",
  "options/datetime.md",
  "options/git.md",
  "options/gpg.md",
  "options/graph.md",
  "options/notifications.md",
  "options/profiles/git.md",
  "options/profiles/gpg.md",
  "options/profiles/graph.md",
  "options/profiles/ssh.md",
  "options/profiles/tools.md",
  "options/profiles/ui.md",
  "options/profiles/user.md",
  "options/ssh.md",
  "options/tools.md",
  "options/ui.md",
  "options/user.md"
]
