name: Documentation

on:
  workflow_dispatch:
  push: &triggers
    branches:
      - main
    paths:
      - docs/**/*
  pull_request: *triggers

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: holster
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check formatting
        run: >
          { nix run '.#treefmt' -- docs --ci || true; } && git --no-pager diff --exit-code
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: docs/package-lock.json
      - name: Install npm packages
        run: npm --prefix docs ci --include dev --ignore-scripts --no-audit
      - name: Check links
        run: npm --prefix docs run linkcheck -- --reporters junit --quiet ./ 2>/dev/null
      - name: Publish link check report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          check_name: Link check report
          report_paths: docs/junit-results.xml
          fail_on_failure: true
          fail_on_parse_error: true
          comment: true
          updateComment: true

  build:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: holster
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build documentation
        run: nix-build ./docs --arg isCI $CI
      - name: Upload built documentation
        uses: actions/upload-artifact@v5
        with:
          name: docs
          path: result

  deploy:
    needs: build
    if: success() && github.ref_name == 'main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: holster
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Retrieve built documentation
        uses: actions/download-artifact@v6
        with:
          name: docs
          path: result
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'result'
      - uses: actions/deploy-pages@v4
        id: deployment
